# Generated by Django 4.2.7 on 2024-06-01 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_producto_idproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('idEvento', models.AutoField(primary_key=True, serialize=False)),
                ('NroParticipantes', models.IntegerField()),
                ('Beneficio', models.CharField(max_length=50)),
                ('Mensaje', models.CharField(max_length=500)),
                ('FechaInicio', models.DateField()),
                ('FechaFinal', models.DateField()),
                ('imagen', models.ImageField(null=True, upload_to='eventos')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'db_table': 'Evento',
            },
        ),
        migrations.AlterField(
            model_name='descuento',
            name='imagen',
            field=models.ImageField(null=True, upload_to='descuentos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
