# Generated by Django 4.2.7 on 2024-06-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_carrito_producto_descripcion_orden_mensaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='ArchivoPDF',
            field=models.FileField(blank=True, null=True, upload_to='facturas/%Y/%m/%d'),
        ),
    ]
