# Generated by Django 4.2.7 on 2024-06-01 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_b2c', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
